### ISSUE TITLE
Compile failed on Mac OSX 10.7

### ISSUE THREAD

**Issue by happyhub** [joeferner/wxNode#1]
/usr/local/lib/node_modules/wxnode/src-generated/wxNode_wxTopLevelWindow.cpp: In static member function ‘static v8::Handlev8::Value wxNode_wxTopLevelWindow::_SetRepresentedFilename(const v8::Arguments&)’:
/usr/local/lib/node_modules/wxnode/src-generated/wxNode_wxTopLevelWindow.cpp:1504: error: ‘class wxNode_wxTopLevelWindow’ has no member named ‘SetRepresentedFilename’

**Comment by joeferner** [comment]
I just published a new version to npm that uses wxWidgets 2.9.3 see if that fixes your problem. Previously I was compiling against wxWidgets 3.x svn source.

**Comment by happyhub** [comment]
[22/35] cxx: src-generated/wxNode_wxMenu.cpp -> build/Release/src-generated/wxNode_wxMenu.o

/Developer/Repository/wxNode/src-generated/wxNode_wxMenu.cpp: In static member function ‘static v8::Handlev8::Value wxNode_wxMenu::_FindChildItem(const v8::Arguments&)’:

/Developer/Repository/wxNode/src-generated/wxNode_wxMenu.cpp:2001: error: no matching function for call to ‘wxNode_wxMenu::FindChildItem(int&, unsigned int*)’

/usr/local/include/wx-2.9/wx/menu.h:305: note: candidates are: wxMenuItem\* wxMenuBase::FindChildItem(int, size_t*) const

[29/35] cxx: src-generated/wxNode_wxSizer.cpp -> build/Release/src-generated/wxNode_wxSizer.o
/Developer/Repository/wxNode/src-generated/wxNode_wxSizer.cpp: In static member function ‘static 
v8::Handlev8::Value wxNode_wxSizer::_Show(const v8::Arguments&)’:

/Developer/Repository/wxNode/src-generated/wxNode_wxSizer.cpp:2362: error: call of overloaded ‘Show(unsigned int&)’ is ambiguous

/usr/local/include/wx-2.9/wx/sizer.h:686: note: candidates are: bool wxSizer::Show(wxWindow*, bool, bool) <near match>

/usr/local/include/wx-2.9/wx/sizer.h:687: note:                 bool wxSizer::Show(wxSizer*, bool, bool) <near match>

/usr/local/include/wx-2.9/wx/sizer.h:688: note:                 bool wxSizer::Show(size_t, bool)

/usr/local/include/wx-2.9/wx/sizer.h:704: note:                 void wxSizer::Show(bool)

**Comment by happyhub** [comment]
When I run 'rendertemplate.js', I got:

skipping wxNode_wxControlWithItems.cpp crc match
Unhandled return type { id: '_909',
  name: '_GtkWidget',
  context: '_1',
  incomplete: '1',
  mangled: '10_GtkWidget',
  demangled: '_GtkWidget',
  location: 'f119:3320',
  file: 'f119',
  line: '3320',
  artificial: '1',
  align: '8',
  elementName: 'Struct',
  pointers: '*',
  refs: '' }

Error: #error("unhandled argCode type '_GtkWidget'")

RENDER: generic.h -> wxNode_wxWindow.h
skipping wxNode_wxWindow.h crc match
Unhandled return type { id: '_909',
  name: '_GtkWidget',
  context: '_1',
  incomplete: '1',
  mangled: '10_GtkWidget',
  demangled: '_GtkWidget',
  location: 'f119:3320',
  file: 'f119',
  line: '3320',
  artificial: '1',
  align: '8',
  elementName: 'Struct',
  pointers: '*',
  refs: '' }

Error: #error("unhandled argCode type '_GtkWidget'")

Environment: wxWidgets 2.9.3.1 compiled with --with-cocoa.

**Comment by joeferner** [comment]
I don't have access to a mac until tomorrow. I just added instructions to the readme on building the api from scratch. Take a look at [https://github.com/joeferner/wxNode#create-wxapi] and see if you can get that to work, otherwise I'll check it out tomorrow and see if I can get it to work on my co-worker's mac.

The unhandled GtkWidget type is fine.

**Comment by happyhub** [comment]
ok. I will read the readme and learn how to make it work. Could you add wxWebView and wxHttp to the template?:). I am designing a tool and I want to write it in wxNode.

**Comment by image72** [comment]
I build **wxNode latest** with node-v0.8.0 in x86/win7 used vc++10
throw that error.

```
F:\dev\wxNode>node mnm.js build
path.existsSync is now called `fs.existsSync`.
wxapi.json read
json parsed
RENDER: generic.h -> wxNode_wxMenu.h

F:\dev\wxNode\node_modules\mustache\mustache.js:386
    throw new Error("Invalid tags: " + tags.join(" "));
                                            ^
TypeError: Object #<Object> has no method 'join'
    at escapeTags (F:\dev\wxNode\node_modules\mustache\mustache.js:386:45)
    at parse (F:\dev\wxNode\node_modules\mustache\mustache.js:471:18)
    at Renderer.compile (F:\dev\wxNode\node_modules\mustache\mustache.js:227:16)

    at Object.compile (F:\dev\wxNode\node_modules\mustache\mustache.js:582:22)
    at F:\dev\wxNode\render-templates.js:755:27
    at fs.readFile (fs.js:176:14)
    at Object.oncomplete (fs.js:297:15)

```
